theme: jekyll-theme-cayman
title: Brandi Stroud
description: Welcome to my website! I am a Computer Science student at the University of Texas at Austin. My site is currently under construction, so keep checking back as I get this off the ground.
